### ISSUE TITLE
Towing works only for the player who placed tow rope

### ISSUE THREAD

**Issue by Tuupertunut** [rekterakathom/Overthrow#50]
**Actual behavior:**
If the player who placed the tow rope is driving the towing vehicle, the rope stays constant length and the towed vehicle moves. If someone else is driving, the rope will just stretch forever and the towed vehicle will not move.

**Expected behavior:**
The towed vehicle should move regardless of who is driving it.

**Comment by rekterakathom** [comment]
ACE issue?

**Comment by Tuupertunut** [comment]
May be, at least it happens in Overthrow.

**Comment by rekterakathom** [comment]
I'll be closing this.

I am fairly certain that this was a bug with ACE towing, I had it appear when playing Antistasi with ACE 3.16.3, but since then ACE has released a refactor to the towing code, and it *should* now work.

Sorry for the low quality photo, but this is from Antistasi, showing the infinite rope stretch.
![image](https://github.com/rekterakathom/Overthrow/assets/30532050/d989b4cd-7705-4964-9f0e-ea17a3acd248)
